export default {
  GET_REQUEST: '@plan/GET_REQUEST',
  GET_SUCCESS: '@plan/GET_SUCCESS',
  GET_FAILURE: '@plan/GET_FAILURE',

  DELETE_REQUEST: '@plan/DELETE_REQUEST',
  DELETE_SUCCESS: '@plan/DELETE_SUCCESS',
  DELETE_FAILURE: '@plan/DELETE_FAILURE',

  INSERT_REQUEST: '@plan/INSERT_REQUEST',
  INSERT_SUCCESS: '@plan/INSERT_SUCCESS',
  INSERT_FAILURE: '@plan/INSERT_FAILURE',

  UPDATE_REQUEST: '@plan/UPDATE_REQUEST',
  UPDATE_SUCCESS: '@plan/UPDATE_SUCCESS',
  UPDATE_FAILURE: '@plan/UPDATE_FAILURE',
};
