export default {
  GET_REQUEST: '@students/GET_REQUEST',
  GET_SUCCESS: '@students/GET_SUCCESS',
  GET_FAILURE: '@students/GET_FAILURE',

  DELETE_REQUEST: '@students/DELETE_REQUEST',
  DELETE_SUCCESS: '@students/DELETE_SUCCESS',
  DELETE_FAILURE: '@students/DELETE_FAILURE',

  INSERT_REQUEST: '@students/INSERT_REQUEST',
  INSERT_SUCCESS: '@students/INSERT_SUCCESS',
  INSERT_FAILURE: '@students/INSERT_FAILURE',

  UPDATE_REQUEST: '@students/UPDATE_REQUEST',
  UPDATE_SUCCESS: '@students/UPDATE_SUCCESS',
  UPDATE_FAILURE: '@students/UPDATE_FAILURE',
};
